### ISSUE TITLE
Error with the new version 0.7.1

### ISSUE THREAD

**Issue by Astrareach** [AppleDash/SaneEconomy#10]
I cant reopen the #9 issue so i create a new one, with the new version 0.7.1 i got an error http://pastebin.com/0bTYmnDc 
also the message.yml keep resetting when i use special caracter http://pastebin.com/isnRnT3T
I put more precision in the last post in the plugin page [https://www.spigotmc.org/threads/saneeconomy-simple-but-featureful-economy.163363/page-2](url)
Thanks again ^^

**Comment by AppleDash** [comment]
The first issue means there is something wrong with your database.
The second, search up on Google how to put special characters like `'` in YAML strings.

Also, you are using the file wrong, see the example at the top.

**Comment by Astrareach** [comment]
Ah i see it now in the message.yml file ... what noob am i, sorry for that. it work now :+1: 
For the Database i will check it more in detail
