### ISSUE TITLE
Towny

### ISSUE THREAD

**Issue by SaltySomeone** [AppleDash/SaneEconomy#12]
I've had complaints of taxes kicking out players even when they have the amount needed to pay the tax. I don't think towny is pulling from SaneEconomy or something..

I have little knowledge to what's going on, but does this sound possible, or is it fixable?

**Comment by AppleDash** [comment]
It should be working fine... Not entirely sure what could be wrong. Also, I am on vacation right now, sorry for response.

**Comment by AppleDash** [comment]
Closing due to no response and confusing issue description. Please reopen if this persists.
