### ISSUE TITLE
No Flatfile

### ISSUE THREAD

**Issue by Genoay** [AppleDash/SaneEconomy#16]
Hi AppleDash,
Installed your plugin, no error messages, however on checking the plugin folder there is no flat file but it has created an "economy.db" file which errors with an "Invalid File Format" on opening. There is no structure or data in the database.
The config file says the backend should be a flat file and there is no mention of a database.
The odd part is that it retains the player balance even after stopping and starting the server and minecraft but I can't find where it is saving it.
Apart from that it is what I have been looking for.
Thanks
Genoay

**Comment by AppleDash** [comment]
I have absolutely no idea what kind of question you are trying to ask me :P 

`economy.db` is the flatfile. That should be easy to deduce with the information you have given me...

(Sorry if I sound condescending, I'm really tired and really confused.)

**Comment by Genoay** [comment]
Sorry, to me .db would be a database and .yml would be a flatfile

**Comment by AppleDash** [comment]
It's a flatfile database - it's just not a human-readable one.

Any reason you need to open it? If you need to edit it externally, I would suggest using MySQL.

**Comment by Genoay** [comment]
Thanks for that. It isn't important to open, if I could have I would to check transactions etc., easier than querying each player ingame.
Thank you very much for your help.
Genoay
