### ISSUE TITLE
Prefix for transations_logs

### ISSUE THREAD

**Issue by NotJustPizza** [AppleDash/SaneEconomy#21]
@Bug
I have name duplication for transations_logs table in my database, could you please add "saneeconomy_" prefix like for other tables?

@Feature_request @Improve_standards
It will be awesome if you add option for customizing table prefix, so it will be posible to store more than one instance of plugin in one database, eg. "se1_", "se2_".

**Comment by AppleDash** [comment]
I can look into this in a little bit, sorry for being inactive - been busy later!

**Comment by AppleDash** [comment]
This will be in a new version soon.

**Comment by AppleDash** [comment]
Fixed in 0.9.2. `table_prefix` config option under `backend`.
