### ISSUE TITLE
Player Names instead of UUID

### ISSUE THREAD

**Issue by augustresende** [AppleDash/SaneEconomy#22]
You can add a config to store player names instead of UUID? Is better for my offline minecraft server, that not require UUID, and is better for my APIs. Please :(

**Comment by AppleDash** [comment]
In what way is it better?

**Comment by augustresende** [comment]
Is better for my server! Is more easy change database values with player names instead of UUID, in my PHP APIs

**Comment by augustresende** [comment]
What is your IDE?

**Comment by CaptainDapper** [comment]
If you're using PHP, you can very easily use Mojang's API (http://wiki.vg/Mojang_API) to go back and forth between UUIDs and PlayerNames.

**Comment by augustresende** [comment]
I can't, my server is for "cracked" players

**Comment by MGAndreasen** [comment]
If your server is for cracked players, how does minecraft know your players inventory when they relogin?  I will assume the server generates somekinda UUID even for cracked servers, might be wrong, but it does not make much sence else to have UUID info internaly on the server if it uses player names.

You could make your own table for conversion from your player names to what ever UUID is assigned to that cracked player,

**Comment by Malachiel87** [comment]
I would like to add a config that use player name instead uuid

**Comment by sgdc3** [comment]
@GabrielAugustoTI What's the issue with offline UUIDs?
