### ISSUE TITLE
Flatfile <----> MySQL or SQLite Conversion?

### ISSUE THREAD

**Issue by goswald** [AppleDash/SaneEconomy#23]
Good evening!

I was wondering, if it isn't already a feature - would there be a way to convert back and forth between the flat file, and MySQL?  Currently, I have a plugin that works off of a SQLite Database.  I don't mind using MySQL for it - our current host has MySQL - but I don't know SQL, so I wouldn't know what commands to run in order to populate a MySQL table from a SQLite table or a flat file, and I'd rather not lose my users' established data.

Does your plugin convert from flat file to MySQL?  If not, would that be possible/easy enough to add?

Alternately, and I know it's a lot to ask, but would it be possible to write SQLite compatibility with it?

Thank you for your time!

**Comment by AppleDash** [comment]
Check the `old-backend` section here :) https://github.com/AppleDash/SaneEconomy/wiki/Configuration
