### ISSUE TITLE
Plugin stops working after restart

### ISSUE THREAD

**Issue by AlmightyAbraham** [AppleDash/SaneEconomy#29]
Hello
The deal is when I first download/launch the plugin everything is working fine but when I set the money of a player it still works fine till the server restart as then there's an error which you can see here from my console report. Personally I think it has something to do with the flatfile which after restart creates the file (economy.db)
Would appreciate any help

17.01 11:30:44 [Server] INFO at org.appledash.saneeconomy.SaneEconomy.onEnable(SaneEconomy.java:45) ~[?:?]
17.01 11:30:44 [Server] INFO at org.appledash.saneeconomy.SaneEconomy.loadConfig(SaneEconomy.java:100) ~[?:?]
17.01 11:30:44 [Server] INFO at org.appledash.saneeconomy.utils.SaneEconomyConfiguration.loadEconomyBackend(SaneEconomyConfiguration.java:49) ~[?:?]
17.01 11:30:44 [Server] INFO at org.appledash.saneeconomy.economy.backend.type.EconomyStorageBackendFlatfile.reloadDatabase(EconomyStorageBackendFlatfile.java:46) ~[?:?]
17.01 11:30:44 [Server] INFO java.lang.ClassCastException: java.util.concurrent.ConcurrentHashMap cannot be cast to java.util.HashMap
17.01 11:30:44 [Server] **ERROR Error occurred while enabling SaneEconomy v0.10.0 (Is it up to date?)**
17.01 11:30:44 [Server] INFO Performing initial data load...
17.01 11:30:44 [Server] INFO Initialized flatfile backend with file /plugins/SaneEconomy/economy.db
17.01 11:30:44 [Server] INFO Initializing economy storage backend...
17.01 11:30:44 [Server] INFO Initialized currency: dollars
17.01 11:30:44 [Server] INFO Initializing currency...
17.01 11:30:44 [Server] INFO Enabling SaneEconomy v0.10.0

**Comment by AppleDash** [comment]
Try 0.10.1, just released on GitHub.

**Comment by AlmightyAbraham** [comment]
Thanks dude so far it has been working like a charm and I'm not getting that error anymore. 
Good job
