### ISSUE TITLE
no way to create an account?

### ISSUE THREAD

**Issue by smmmadden** [AppleDash/SaneEconomy#32]
Hi, I'm trying to switch from Fe economy to SaneEconomy and one thing I'm finding missing is the option to create an account.  The account is not a player, but the "server bank account" which I could create in Fe and then reference in the Jobs Reborn plugin as my server-side bank.  This is the account that all players get paid from.  So since I removed Fe from my test server, when I break or place a block that should be paying me, I get a message stating "Sorry, no money left in national bank!"  Is there a reason this was left off this plugin or an alternative way to do the same?
Thanks - Steve

**Comment by AppleDash** [comment]
Hmm, that's a bit weird... The Jobs Reborn plugin should just be "spawning in" money to pay players with. Have you asked their developers if there's an option for this?

**Comment by smmmadden** [comment]
I have, waiting to hear back from him to see if he can add the extra parameter to create it, if it is set to use a server account.  Having it included though in SaneEconomy does make sense as all the other options are there to check a balance, pay a player, give, take and set but no create or remove/deleting an account.  Add that and I bet a lot of folks would be happy. :-)

**Comment by smmmadden** [comment]
Hi AppleDash, he's looking into the code for Jobs Reborn to see if it can work, but he pretty much said the economy plugins should have the option to create server or player accounts which I do agree since that's what I'm trying to do is create an account that will be used as the paying Bank to players.  Have you had any luck with looking at source to see if it is feasible?

**Comment by smmmadden** [comment]
Any update - is this something you are able to support?  Thanks!

**Comment by AppleDash** [comment]
Sorry, been out of the house - this is feasible and I will add a command to create a server account when I have a moment. Should be in the next couple days :)

**Comment by AppleDash** [comment]
Give it a go now - there's a new config option, check the wiki.
