### ISSUE TITLE
Database connection pool

### ISSUE THREAD

**Issue by huluhulua** [AppleDash/SaneEconomy#33]
I am using mysql. In my server there are too many connections in TIME_WAIT stat. Every new mysql connection have to do authentication each time. I think you can use a connection pool library to improve  the performance, [HikariCP](https://github.com/brettwooldridge/HikariCP) is a good one. LogBlock plugin useHikariCP, and it has very a good performance.

**Comment by AppleDash** [comment]
Is this still a trouble with latest version?
