### ISSUE TITLE
Block cross-world /pay

### ISSUE THREAD

**Issue by MystServer** [AppleDash/SaneEconomy#35]
Any way to stop players transferring money between worlds on a multi-world server setup? I've currently had to disable /pay since players could earn money in survival and transfer it to Skyblocks. I also tried using MultiWorldMoney: https://www.spigotmc.org/resources/multi-world-money.6231/
and disabling SaneEconomy's /pay permission and allowing players MWM's /pay but this blocks /pay altogether.
Perhaps I am doing something wrong? Or maybe if it's not added already add support for multi-world servers?

**Comment by AppleDash** [comment]
I thought I replied to this! This plugin is primarily designed for a server where the whole point is earning money in one world and transferring it to another, so I never considered for support of this. You could block economy commands with WorldGuard if that could work? Otherwise I could consider support for multiworld.

**Comment by MystServer** [comment]
Hey! I was honestly surprised but happily so to see your response. My community has certainly gotten enjoyed your resource. For us, we would love to see multi-world support as currently, I've had to disable /pay altogether to avoid money being transferred from survival to skyblocks or even minigames. Unfortunately blocking the command with WorldGuard wouldn't be a solution.  

    On Saturday, June 10, 2017 2:35 PM, AppleDash <notifications@github.com> wrote:
 

 I thought I replied to this! This plugin is primarily designed for a server where the whole point is earning money in one world and transferring it to another, so I never considered for support of this. You could block economy commands with WorldGuard if that could work? Otherwise I could consider support for multiworld.—

**Comment by AppleDash** [comment]
Adding multi-world support will be a big project. If you're willing to wait a little while, then I can do my best to make it happen in the next few weeks 😸

**Comment by A248** [comment]
I could easily make a script with Skript to block cross world pay. You would have to add an entry in your commands.yml in addition to installing Skript.
