### ISSUE TITLE
Is "json" not an option anymore for backend type in the config?

### ISSUE THREAD

**Issue by bindingflare** [AppleDash/SaneEconomy#36]
When i read the wiki, Configuration page, I read that saving the player accounts using json is an option:
![image](https://cloud.githubusercontent.com/assets/18100713/22857069/fc7ce590-f0c3-11e6-9023-cfb5992019dc.png)

But when I try setting the config that way the plugin (SaneEco) does not recognise it:
![image](https://cloud.githubusercontent.com/assets/18100713/22857088/679ec820-f0c4-11e6-8947-1c365307be78.png)

Using Spigot 1.11.2 (Build is latest enough to not give out an outdated build notification at the start)
The server will run fine if i use what i used before (flatfile).

**Comment by AppleDash** [comment]
It is supposed to be an option, but it's not yet implemented in the 
production version - if you build from Git, it works, however.

**Comment by bindingflare** [comment]
Do you mean like clone and export to jar or do something else for build from Git?

**Comment by AppleDash** [comment]
Fixed

**Comment by bindingflare** [comment]
Thanks!
