### ISSUE TITLE
server-account not working

### ISSUE THREAD

**Issue by smmmadden** [AppleDash/SaneEconomy#37]
Thanks for adding this feature.  Unfortunately, the server-account doesn't appear to be working as expected.  I have all the permissions, can use each but when I updated the config.yml to have
start-balance: 100000000000.00
server-account: MC-Bank  (I later changed it to $MC-Bank$ and then started getting paid by it)
The server-account name should be like a player, but not, so it seems it isn't quite registering.

/baltop should show it as the top account followed by my account.  Instead, the first time it said "There aren't enough players to display that page."  Which is strange, like there has to be a minimum more than 1?  My name wasn't listed, so I set my balance and tried again, then I see [01] smmmadden - 10.14 dollars which is good.  But the server-account should always be listed too.  Otherwise, there is no way to tell if the server needs more money or not.  Yes, we would want to know what the current balance is.

/bal MC-Bank (or lower-cased) says "That player does not exist." which gives the impression the account doesn't exist even though the config shows that it does.

I also removed Fe.jar and the folder, restarted and the config.yml updated the start-balance to 1.0E9 which isn't typical that you'd see for an amount.  I tried getting paid for breaking blocks and my balance never changed.  It was only when I put a $ before and after the server-account name ($MC-Bank$)

What's strange is though I downloaded the 10.5 version (from Spigot & Github), when I logged in, the server thinks it is 10.4.  I tried both files with and without SNAPSHOT in the name.  Still registering as 10.4. The first restart of the server, I logged in and it showed my balance with 100,000,000,000.00.  I set my player name balance to 10.14 and then it showed correctly.  But still not getting paid 
What I see after logging in, the chat window shows:
**[Economy] An update is available! The currently-installed version is 0.10.4, but the newest available is 0.10.5. Please go to https://github.com/AppleDash/SaneEconomy/releases to update!**

**Comment by AppleDash** [comment]
`start-balance` is the balance that every *player* starts with on join. The server account doesn't have any kind of balance, and never needs to be refilled - any transaction made by a plugin using the API with the server account as the account name will always succeed, acting as if that account has an infinite balance. You can't check it's balance because `/bal` only works on real players.

As for the update thing - oops, 0.10.6 will fix it :)

**Comment by smmmadden** [comment]
I see - not quite what I was expecting but I guess it would work for some worlds that don't want to manage the transactions from the server.  From my perspective, we have a server account that acts as the clearing account for all transactions like The World Bank (real entity).  The bank can be paid directly by players for purchasing properties on a world.  The bank can also pay out, provide loans and many other aspects.  So it is a virtual player if you get that.  Being able to set its starting balance, monitoring it for fraud (cheating) and making sure it rates along with other players makes sense.  Players would need to know if they can borrow monies from the bank and the bank owner (Admin) needs to know what they've loaned out and to who.  Hope that clarifies what the intent is behind the server account and having the option to Create others as well (but non players) - stores, businesses, etc.  Think real life entities and organizations.  That's what we teach on our servers.  Money isn't infinite, doesn't grow on trees and has to come from somewhere or someone. :-)

**Comment by smmmadden** [comment]
closing this request as it works with the server account being unlimited funds and was able to update JobsReborn plugin to "not use a server account" as there is no way to name a server account in this plugin.  So setting it to false in JobsReborn enables SE to work.
