### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by ardentcrest** [AppleDash/SaneEconomy#39]
can you give me an example config file to use mysql, I cant get mine to work.

> 
01:11:20 [SEVERE] Cannot load plugins\SaneEconomy\config.yml
01:11:20 org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
01:11:20  in 'string', line 3, column 12:
01:11:20        hostname: 'localhost'
01:11:20                ^
01:11:20 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:167) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:142) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.appledash.saneeconomy.SaneEconomy.loadConfig(SaneEconomy.java:86) [SaneEconomyCore-0.10.6-SNAPSHOT.jar:?]
01:11:20 	at org.appledash.saneeconomy.SaneEconomy.onEnable(SaneEconomy.java:45) [SaneEconomyCore-0.10.6-SNAPSHOT.jar:?]
01:11:20 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
01:11:20 Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
01:11:20  in 'string', line 3, column 12:
01:11:20        hostname: 'localhost'
01:11:20                ^
01:11:20 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	... 15 more
01:11:20 [SEVERE] Cannot load plugins\SaneEconomy\config.yml
01:11:20 org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
01:11:20  in 'string', line 3, column 12:
01:11:20        hostname: 'localhost'
01:11:20                ^
01:11:20 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:184) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:179) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:167) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:20 	at org.appledash.saneeconomy.SaneEconomy.loadConfig(SaneEconomy.java:95) [SaneEconomyCore-0.10.6-SNAPSHOT.jar:?]
01:11:20 	at org.appledash.saneeconomy.SaneEconomy.onEnable(SaneEconomy.java:45) [SaneEconomyCore-0.10.6-SNAPSHOT.jar:?]
01:11:20 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:271) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugin(CraftServer.java:376) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.enablePlugins(CraftServer.java:326) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
01:11:21 Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
01:11:21  in 'string', line 3, column 12:
01:11:21        hostname: 'localhost'
01:11:21                ^
01:11:21 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:450) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[spigot-1.11.2.jar:git-Spigot-d4f98a3-cb61ac0]
01:11:21 	... 14 more
>

**Comment by AppleDash** [comment]
Show me your config please.

**Comment by ardentcrest** [comment]
backend:
  type: mysql
  hostname: 'localhost'
  port: '3306'
  username: 'root'
  password: '*******'
  databaseName: '*******'
  prefix: 'economy_'
currency:
  name:
    singular: dollar
    plural: dollars
  format: '0.00'
  grouping: 3
  grouping-separator: ','
chat:
  prefix: '&b[&9Economy&b]&r '
economy:
  start-balance: 0.0
  notify-start-balance: true
  server-account: $SERVER$
debug: false

**Comment by AppleDash** [comment]
Try again, but on a pastebin service. That config is nowhere near properly indented.

**Comment by smmmadden** [comment]
I may be wrong here, but this looks like the config file was never updated to have the actual localhost name, doesn't have access to the database (permissions) or the root account does not exist.  When I installed MySQL, for another plugin, I did not have root as the super user and needed to provide the localhost, different port # (since I never use defaults for security reasons) to use and allow it to be accessed via router settings.  So my first question would be, did you install MySQL using the same defaults on the same server?

**Comment by ardentcrest** [comment]
http://pastebin.com/q75d0r24

**Comment by ardentcrest** [comment]
all my other plugins work with the the database

**Comment by smmmadden** [comment]
thanks for the confirmation - you'd be surprised how many people assume MySQL gets installed automatically because of the settings. :-)

**Comment by AppleDash** [comment]
That config looks valid to me... And matches up reasonably enough with the example. Try recreating it from the example, perhaps.

**Comment by ardentcrest** [comment]
Hummm I still get errors. can you please post a working config file so I can see what it should look like.
