### ISSUE TITLE
Feature or issue? Non-Player accounts.

### ISSUE THREAD

**Issue by FrostTaco** [AppleDash/SaneEconomy#4]
Recently I had an issue with factions, as disbanding would give an error. Was then given a new version of SaneEconomy to fix it. I posted on factions asking them to fix: Invalid player name to a vault api method, and here was the response(I kind of need factions to use the economy, please :P): 

`Factions can have accounts, usually economy plugins handle this farley well.

It seems that they are not fit to handle anything else then players, which iMO is rather weak.

This message would disapear if you disable the economy feature in Factions. But that would also mean that players don't have to pay/ get rewarded for/from factions.

If I were you, I'd post a request on their github to support non-player accounts such as factions.
`

**Comment by AppleDash** [comment]
I would personally consider it a bug - support for non-player accounts should be added, but at the same time, the same API methods shouldn't be used for both players and non-players.

I'm not going to be stubborn on this issue like some plugin developers would. Can you obtain some information from Factions, asking what an account name for a factions looks like in the code? (Example, is it just the faction name or is it something like faction:factionname, or what?)

**Comment by AppleDash** [comment]
The latest version now has support for this, @FrostTaco . There is no release yet, but I will be posting one soon as soon as I do a little bit more testing.

**Comment by AppleDash** [comment]
Considering this closed as support has been added and there have been no further complaints.
