### ISSUE TITLE
Money from votes are not correct

### ISSUE THREAD

**Issue by erik1988** [AppleDash/SaneEconomy#40]
Im using GAListener to give me money for votes on my server. The issue is that your plugin does not work well when it is several votes queued up. This worked well with craftconomy before I switched over btw..

You can see the result here:
http://pastebin.com/7ZJnD0FS
In this case I did not get the money from the second vote. 

If a player does not get a bonus (5 in this example) he would only get the first vote. 
Note that it sometimes works, but it does not work most of the time.

**Comment by ghost** [comment]
I think I've also noticed this issue with any transactions that happen close together, not just votes.

**Comment by AppleDash** [comment]
That's a bit strange - I'll have to look harder at it.

**Comment by AppleDash** [comment]
Should be fixed in the latest Git version - I will release an actual update soon!
