### ISSUE TITLE
Show player names even if player has not been on specific server

### ISSUE THREAD

**Issue by ghost** [AppleDash/SaneEconomy#49]
In a multi-server environment, player's names are shown as null in /baltop if they have an account but have not been on the specific server that /baltop was issued on. This also means that that player's balance cannot be checked from servers they haven't been on. The player's last known name should be stored in the database so it is visible to all servers.

**Comment by AppleDash** [comment]
I'll need to look at this. It will involve removing support for older versions of the plugin which I don't like doing, but I will see what I can do.

**Comment by AppleDash** [comment]
This will be in the latest release.
