### ISSUE TITLE
'Infinite' money. Vault API integration error.

### ISSUE THREAD

**Issue by mbl111** [AppleDash/SaneEconomy#5]
Love the plugin, super light weight and works, mostly. 

You've got a bug though in your Vault hook where currency is withdrawn. You return a transaction SUCCESS even if the players balance is less than the amount being withdrawn. Currently I'm getting problems from plugins which allow users to spend like crazy because of this.

**Comment by AppleDash** [comment]
Whoops, apparently I managed to only test the plugin with plugins that used the vault API in such a way that this didn't break ;)

Uploading build 0.6.2 momentarily, give that a try!

**Comment by AppleDash** [comment]
@mbl111 Any luck with 0.6.2?

**Comment by mbl111** [comment]
Worked perfectly! The plugin now tells me off for being the poor bugger I am :p 
Thanks heaps!

**Comment by AppleDash** [comment]
No problem!
