### ISSUE TITLE
Update check is not checking the latest build properly

### ISSUE THREAD

**Issue by smmmadden** [AppleDash/SaneEconomy#52]
seems we have a disconnect in what the newest version is when we join the game using the 0.12.6 version. Not sure why it thinks that 0.5.7 is the newest as it was done last July (2016). :) 
![image](https://user-images.githubusercontent.com/10309346/28244263-1297b832-69b4-11e7-8c61-9aa947fd4ca3.png)

**Comment by AppleDash** [comment]
Fixed in latest release! Sorry about that :P
