### ISSUE TITLE
A better way to make a locale

### ISSUE THREAD

**Issue by EverNife** [AppleDash/SaneEconomy#53]
I am speding a lot of time just to make it run...

Could you make almost all other plugin and generate a locale.yml on the plugin's folder and then we just need to edit that ?

- - - - - 

Besides that, can you tell me what am i doing wrong?

```
...
  - message: "You don't have permission to check the balance of {1}."
    translation: "&cVocê não tem permissão para ver o saldo do jogador &3{1}."
  - message: "That player is not online."
    translation: "&cEsse jogador não esta online."
  - message: "You cannot pay yourself."
    translation: "&cVocê não pode pagar a si mesmo."
...
```

[messages.yml
](https://hastebin.com/iyafahonun.pl)

**Comment by AppleDash** [comment]
What difference does the filename make? The current method looks fine to me, and makes more sense from a technical perspective as well.

What's wrong with the file you have there? Looks to be working fine for me. I just tested it on a local server.

**Comment by EverNife** [comment]
'-'
For me just does not translate, where i need to let this file ?
Config folder?
Still inside the plugin.jar ?

**Comment by AppleDash** [comment]
The config folder?

**Comment by EverNife** [comment]
forget, got it somehow ^^
