### ISSUE TITLE
Balance changes between servers not reflected immediately

### ISSUE THREAD

**Issue by ghost** [AppleDash/SaneEconomy#57]
If a player gets paid by someone on another server, the expected behavior is that they should be able to see their updated balance immediately with /bal. Instead, the recipient doesn't see their new balance until they relog. This leads to confusion and inconvenience for players. Ideally, players would even receive a notification in chat when they are paid by someone from another server, but I understand that that might not be a trivial addition.

**Comment by AppleDash** [comment]
That's.... hmm, not entirely supported at the moment. I can probably make it work, but it may require a BungeeCord plugin.

**Comment by ghost** [comment]
The simplest solution I can think of is to fetch the player's balance from the database for every query/change of their balance, but that might pose some performance problems.

**Comment by AppleDash** [comment]
Can't do that, that's a major reason most economy plug-ins are slow and bad 

On September 17, 2017 7:50:17 PM EDT, Carter <notifications@github.com> wrote:
>The simplest solution I can think of is to fetch the player's balance
>from the database for every query/change of their balance, but that
>might pose some performance problems.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/AppleDash/SaneEconomy/issues/57#issuecomment-330102572

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sgdc3** [comment]
> That's.... hmm, not entirely supported at the moment. I can probably make it work, but it may require a BungeeCord plugin.

Nope, you can do that with broadcast plugin messages.
https://www.spigotmc.org/wiki/bukkit-bungee-plugin-messaging-channel/#forward

**Comment by sgdc3** [comment]
Without any bungee-side plugin

**Comment by AppleDash** [comment]
@sgdc3 Cool, I'll look into it!

**Comment by AppleDash** [comment]
Can you give this a try for me? https://github.com/AppleDash/SaneEconomy/releases/tag/0.13.0

**Comment by AppleDash** [comment]
Any luck? Try latest release (not that link I gave you.)
