### ISSUE TITLE
Issue with ecoadmin command

### ISSUE THREAD

**Issue by Astrareach** [AppleDash/SaneEconomy#6]
# Hi, i get an error when using the ecoadmin command "/set", "/give" and "/take".

Also, the jar file "SaneEconomyCore-0.6.2-SNAPSHOT.jar" is the SaneEconomy 0.6.1 version

> [13:07:31] [INFO] Anois581 issued server command: /ecoadmin give Anois581 1000
> [13:07:31] [ERROR] null
> org.bukkit.command.CommandException: Unhandled exception executing command 'ecoadmin' in plugin SaneEconomy v0.6.1
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
> at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
> Caused by: java.lang.NumberFormatException: For input string: "1000,00"
> at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_91]
> at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_91]
> at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_91]
> at java.lang.Double.valueOf(Double.java:502) ~[?:1.8.0_91]
> at org.appledash.saneeconomy.utils.NumberUtils.filterAmount(NumberUtils.java:36) ~[?:?]
> at org.appledash.saneeconomy.utils.NumberUtils.parseAndFilter(NumberUtils.java:40) ~[?:?]
> at org.appledash.saneeconomy.command.type.EconomyAdminCommand.onCommand(EconomyAdminCommand.java:66) ~[?:?]
> at org.appledash.saneeconomy.command.SaneEconomyCommand.onCommand(SaneEconomyCommand.java:23) ~[?:?]
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> ... 15 more

Thanks in advance for your help

**Comment by AppleDash** [comment]
The JAR thing is known - it's actually 0.6.2, I promise - the version # is just wrong. I'll publish an 0.6.3 soon to fix the version # issue.

As for your error - can you please post me your config.yml from the SaneEconomy folder in your plugins folder? Thanks!

**Comment by Astrareach** [comment]
Ok this is great !

Here is the config.yml (that got reset 20 minute ago at the server restart)

http://pastebin.com/Jh8XpBmS

**Comment by AppleDash** [comment]
I think I've fixed the issue - try this attached file?
[SaneEconomyCore-0.6.3-SNAPSHOT.zip](https://github.com/AppleDash/SaneEconomy/files/390454/SaneEconomyCore-0.6.3-SNAPSHOT.zip)

**Comment by Noiknez** [comment]
Got an error :

**Comment by Astrareach** [comment]
With this version i got :

> [14:01:36] [INFO] Anois581 issued server command: /ecoadmin set Anois581 5
> [14:01:36] [ERROR] null
> org.bukkit.command.CommandException: Unhandled exception executing command 'ecoadmin' in plugin SaneEconomy v0.6.4
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) ~[minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
> at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
> at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
> Caused by: java.lang.NumberFormatException: For input string: "5,00"
> at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043) ~[?:1.8.0_91]
> at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:1.8.0_91]
> at java.lang.Double.parseDouble(Double.java:538) ~[?:1.8.0_91]
> at java.lang.Double.valueOf(Double.java:502) ~[?:1.8.0_91]
> at org.appledash.saneeconomy.utils.NumberUtils.filterAmount(NumberUtils.java:45) ~[?:?]
> at org.appledash.saneeconomy.utils.NumberUtils.parseAndFilter(NumberUtils.java:49) ~[?:?]
> at org.appledash.saneeconomy.command.type.EconomyAdminCommand.onCommand(EconomyAdminCommand.java:67) ~[?:?]
> at org.appledash.saneeconomy.command.SaneEconomyCommand.onCommand(SaneEconomyCommand.java:23) ~[?:?]
> at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[minecraft_server.jar:git-Spigot-078e2f8-21e3b05]
> ... 15 more

**Comment by AppleDash** [comment]
Whoops, sorry, wrong file uploaded - try this one!

[SaneEconomyCore-0.6.4-SNAPSHOT.zip](https://github.com/AppleDash/SaneEconomy/files/390529/SaneEconomyCore-0.6.4-SNAPSHOT.zip)

**Comment by Astrareach** [comment]
The ecoadmin commands now work perfectly without error ! Thank you for the help !
