### ISSUE TITLE
SaneEconomy

### ISSUE THREAD

**Issue by MichaelMBrown** [AppleDash/SaneEconomy#61]
Hey, I recently just downloaded this plugin and its really nice, except for the fact that in all of the messages it is prefixed SaneEconomy<message>. There isn't a space between the y and the < because, in chat they are combined. Here's my messages.yml (Open with Notepad++ or Visual Studio Code). 
!
[sane](https://user-images.githubusercontent.com/13665728/31571242-9bd9ae40-b05c-11e7-94c6-79f888ede90b.PNG)
[messages.txt](https://github.com/AppleDash/SaneEconomy/files/1384315/messages.txt)

**Comment by AppleDash** [comment]
Reopen if still broken.
