### ISSUE TITLE
Multicurrency support

### ISSUE THREAD

**Issue by DJIronic** [AppleDash/SaneEconomy#62]
Hi, 

I want to ask your, if there it possible to add two currencies. I want to have one currency as the main in-game one and then second currency used as premium one. I don´t need to use the game so much.

I just want to let players pay with the normal currency and use the premium currency to buys VIP and pay in playerserver plugin.

Is that possible? Thanks :)

**Comment by AppleDash** [comment]
This is not on the roadmap. Sorry.
