### ISSUE TITLE
Balance not updated cross-server

### ISSUE THREAD

**Issue by ghost** [AppleDash/SaneEconomy#68]
If money is sent to an offline player from Server A and then their balance is checked from Server B, the balance will not show the updated amount. I have not tested this with online players, but balance should be updated regardless of if a player is online or not.

**Comment by ghost** [comment]
Confirmed to also not work with two online players on separate servers. If player A sends money to player B on separate servers, player B cannot see their updated balance until they relog. I have `multi-server-sync: true` in all of my servers' config.yml files.

**Comment by AppleDash** [comment]
Do you get an exception in the console?

**Comment by ghost** [comment]
@AppleDash Nothing.

**Comment by AppleDash** [comment]
:(
