### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by zBoringDrop** [AppleDash/SaneEconomy#74]
hey, maybe you can add in this plugin the possibility of convert the flat database of the bukkit plugin gMoney to this pl.
Can you do this?

**Comment by AppleDash** [comment]
If gMoney supports Vault, then `/vault-convert` can do it.

**Comment by zBoringDrop** [comment]
Can you send me the COMPLETE command?
Because i alredy did this, but 0 files was created

**Comment by zBoringDrop** [comment]
so @AppleDash ?

**Comment by AppleDash** [comment]
I don't really know.
