### ISSUE TITLE
Baltop Errors

### ISSUE THREAD

**Issue by A248** [AppleDash/SaneEconomy#76]
Hi, upon execution of the command /baltop two issues arise.

1. The tenth player is displayed first.
The baltop page looks like:
[10] <player> <money>
[1] <player> <money>
[2] <player> <money>
[3] <player> <money>
...
and so on

2. I don't show up on the bal top page, but my balance is greater than the first player.

Note: Executed command from console.
https://pastebin.com/84M4BS3A

**Comment by AppleDash** [comment]
What country are you in?

**Comment by A248** [comment]
I'm in the U.S.; my server is hosted in Montreal.
