### ISSUE TITLE
grouping separator and server account doesn't work

### ISSUE THREAD

**Issue by bigyoor** [AppleDash/SaneEconomy#77]
Hello, hope you read that soon!
(sorry for my bad english)

I have two bugs to report:

1-when the grouping separator on values is activated , player accounts are randomly reseted

2-I've edited in the config the name of server account , but this one does'nt appears anywhere :/

sadly, no console error logs

**Comment by AppleDash** [comment]
1) I'll have to look into that, I would not recommend changing it honestly.
2) Where do you expect it to appear?

**Comment by bigyoor** [comment]
thanks for answer,

okay, it's not really important but hope that will be fix , it make the values more visible on big prices

for the server account, i would it appears on "/eco" or "/money" like a player. (at this moment it looks infinite but i can't check it)

**Comment by AppleDash** [comment]
1) Sorry about that, grouping-separator and everything to do with it are hella buggy for unknown reasons.
2) If a plugin attempts to deposit to the server-account, it goes nowhere. If a plugin attempts to withdraw from the server account, it always succeeds.
