### ISSUE TITLE
Other Locales

### ISSUE THREAD

**Issue by YTKacperSKY** [AppleDash/SaneEconomy#78]
Can you implement a Locale variable to your `formatAmount(double amount)` and put it in the config, so for example a german server uses 1.000,00 and US uses 1,000.00 and with `Locale.GERMANY` you can change that.
```java
Locale locale = Locale.GERMANY;
String string = NumberFormat.getNumberInstance(locale).format(-1234.56);
```
you can use this to save in cofig
`Locale locale = Locale.forLanguageTag("en-US");`

**Comment by AppleDash** [comment]
Why not just correctly configure your operating system's locale?
