### ISSUE TITLE
Small error

### ISSUE THREAD

**Issue by ghost** [AppleDash/SaneEconomy#79]
Got this error when starting the plugin:

23.03 10:51:35 [Server] WARN SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder". 
23.03 10:51:35 [Server] WARN SLF4J: Defaulting to no-operation (NOP) logger implementation 
23.03 10:51:35 [Server] WARN SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

I also got this error:
25.03 22:28:41 [Server] WARN [SaneEconomy] SaneDatabase didn't terminate all threads, something weird is going on?

I dont know if this is an error or something in that direction, but I thought i'd let you know :)

**Comment by AppleDash** [comment]
Says on the Spigot page that it can be ignored.

On March 23, 2018 5:53:34 AM EDT, Julianvb97 <notifications@github.com>
wrote:

    Got this error when starting the plugin:

    23.03 10:51:35 [Server] WARN SLF4J: Failed to load class
    "org.slf4j.impl.StaticLoggerBinder".
    23.03 10:51:35 [Server] WARN SLF4J: Defaulting to no-operation (NOP)
    logger implementation
    23.03 10:51:35 [Server] WARN SLF4J: See
    http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

    I dont know if this is an error or something in that direction, but
    I thought i'd let you know :)

    —
    You are receiving this because you are subscribed to this thread.
    Reply to this email directly, view it on GitHub
    <https://github.com/AppleDash/SaneEconomy/issues/79>, or mute the
    thread
