### ISSUE TITLE
Tells me to update, but is updated.

### ISSUE THREAD

**Issue by TrademarkTM** [AppleDash/SaneEconomy#8]
Hey!
I'm using SaneEconomy 0.6.5 (I downloaded from Spigot and GitHub), but it says there's a new version. Also, in /version SaneEconomy it appears as 0.6.4 (and in my /plugins folder the name is 0.6.5). Could you fix this? Thanks!

**Comment by AppleDash** [comment]
Sorry about that - I keep messing that up xD About to post v0.6.6 that fixes this again.

**Comment by AppleDash** [comment]
https://github.com/AppleDash/SaneEconomy/releases/tag/0.6.6
