### ISSUE TITLE
Configuration resets

### ISSUE THREAD

**Issue by Resoluciones** [AppleDash/SaneEconomy#83]
Hi! Great plugin! Congratulations!

Can you pls. give me an complete example of a mysql configuration?  Every time I set

` backend:
    type: mysql`
  
  the configuration resets to its default.
  
Let me know!

Thanks!!!

**Comment by AppleDash** [comment]
If that is actually what your config looks like, with that format, there is your problem. You need to use YAML properly. eg:

```
backend:
  type: mysql
```

**Comment by Resoluciones** [comment]
Hi AppleDash, sorry for not putting it in the right format here in the issues section, yes YAML was used of course!  Maybe is it not compatible with paper?

**Comment by fnutt** [comment]
It is compatible with Paper. It works on my network with Paper servers.

**Comment by AppleDash** [comment]
Works fine with Paper. Sorry for the delay in responding. Did you ever get it working?
