### ISSUE TITLE
MySQL issue

### ISSUE THREAD

**Issue by VergilPrime** [AppleDash/SaneEconomy#84]
Using SaneEconomy 0.13.1 and MariaDB on a Ubuntu server.

I assume this issue is something I am doing wrong but it's not happening with any of the other plugins I have which use MySQL as a backend.

https://paste.thezomg.com/73996/34143651/

What permissions does SaneEconomy need? I have a feeling I'm not granting perms right on my database, but as I said the rest are working so I'm not sure.

**Comment by AppleDash** [comment]
Indeed it looks like a permissions issue, which you have probably fixed by now.
