### ISSUE TITLE
Data not saving in MySQL

### ISSUE THREAD

**Issue by Astrareach** [AppleDash/SaneEconomy#9]
Greeting !
I got a problem with saneeconomy not saving players balance into MySQL, it connect properly to it without error message. This happen when i restart the server and when i reload the saneeco database

Spigot version : CraftBukkit version git-Spigot-90f61bc-83a9dbd (MC: 1.10.2) 
SaneEco version : SaneEconomyCore-0.6.6-SNAPSHOT
SaneEco config.yml : http://pastebin.com/QmghU6cM

SaneEconomy connection to database : http://pastebin.com/NrbEicaZ
(Everytime the same "Performing initial data load..." message at server restart)
Database-reload command proof : http://pastebin.com/Lh5JGjML

Nevertheless, flatfile is working perfectly
Sadly, i also get the same problem with version 0.6.4

**Comment by AppleDash** [comment]
That's an interesting problem. Can you check your database, and see if there is actually any SaneEconomy tables in your database, and any data in the tables?

(Also, the "Performing initial data load" message is expected - it needs to load all the data at server startup, so it does so.)

**Comment by Astrareach** [comment]
The SaneEconomy table is present : http://prntscr.com/c1zgcd
Saneeconomy_balance is empty : http://prntscr.com/c1zh5i
But Saneeconomy_shema is not empty : http://prntscr.com/c1zhcm

Ah ok, it was just the "itinial' word that i do comprehend differently!
Also i test with different player and same problem of not saving at db reload

**Comment by AppleDash** [comment]
Hmm, that's interesting! Do you have any errors in console when you do
/eco give your_minecraft_name 1000 ?

**Comment by Astrareach** [comment]
No error :

> [16:24:30] [INFO] [Economy] Added 1000,00 units to naeliks. Their balance is now 1000,00 units.

**Comment by AppleDash** [comment]
And after you do that... Nothing in the database still?

**Comment by Astrareach** [comment]
Nothing in the database balance table after setting a balance to a player, me or someone sadly : http://prntscr.com/c202h3

**Comment by AppleDash** [comment]
That is very interesting... I will get back to you, hopefully by
tomorrow. In the mean time, use Flatfile - once I solve this, I will add
a command to convert Flatfile to MySQL.

**Comment by AppleDash** [comment]
This is a very weird issue... I'm having problems finding the cause. I know it has to do with the fact you are in France (or Quebec), however.

**Comment by Astrareach** [comment]
No problem, i surely can wait; its a french server, if you need more information about my host or the mysql host, i can give you that

**Comment by jack-the-cat** [comment]
Hey AppleDash (and Noiknez, sorry to crash your thread :) ). I've got the same issue on my server too... Your plugin functions normally with no error messages, but doesn't add data to the database at all. It creates the tables as normal, but doesn't enter any data.

**Comment by AppleDash** [comment]
Fixed it now @Noiknez  and @twaitsey !

Try this release: https://github.com/AppleDash/SaneEconomy/releases/tag/0.7.1

To convert data from Flatfile to MySQL, configure MySQL as normal and then add a section like this:

```
old-backend
  type: flatfile
```

Conversion will automatically happen on server restart.

**Comment by AppleDash** [comment]
Please reopen this if the problem persists :)

**Comment by Astrareach** [comment]
Hi again, with this version i got this error http://pastebin.com/0bTYmnDc
No problem to connect to the mysql therefore ^^
