### ISSUE TITLE
/money translete problem

### ISSUE THREAD

**Issue by YumeRacing** [AppleDash/SaneEconomy#99]
Hey!
I love your Plugin, thank you so much for all your work. I just have one small Problem. in the config i can change every message that is shown in the chat, but i cant change the message that pops up, then you do /money.
It is: Your balance is 1000 dollars.
Where can i change this message ? :)
I would be so thankful if you could help me :)

**Comment by AppleDash** [comment]
translations.yml, check the wiki please
